// Codegen: embeds packages/core/assets/publish-data/** and pako_inflate.min.js
// into src/generated/publish-assets.ts as plain strings, so the core has the
// injected network scripts and the imba inflater inline — no fetch, no fs.
import { promises as fs, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const coreDir = path.resolve(__dirname, "..");
const assetsDir = path.join(coreDir, "assets");
const publishDataDir = path.join(assetsDir, "publish-data");
const pakoPath = path.join(assetsDir, "pako_inflate.min.js");
const outFile = path.join(coreDir, "src", "generated", "publish-assets.ts");

async function walk(dir) {
  if (!existsSync(dir)) return [];
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(full)));
    else files.push(full);
  }
  return files;
}

async function main() {
  const files = (await walk(publishDataDir)).sort();
  const map = {};
  for (const file of files) {
    const rel = path.relative(publishDataDir, file).split(path.sep).join("/");
    map[rel] = await fs.readFile(file, "utf8");
  }
  const pako = existsSync(pakoPath) ? await fs.readFile(pakoPath, "utf8") : "";

  let body = "// AUTO-GENERATED by scripts/embed-assets.mjs. Do not edit by hand.\n\n";
  body += "export const PUBLISH_ASSETS: Record<string, string> = {\n";
  for (const [key, value] of Object.entries(map)) {
    body += `  ${JSON.stringify(key)}: ${JSON.stringify(value)},\n`;
  }
  body += "};\n\n";
  body += `export const PAKO_INFLATE_MIN: string = ${JSON.stringify(pako)};\n`;

  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, body, "utf8");
  console.log(
    `[embed-assets] ${Object.keys(map).length} publish-data file(s) + pako (${pako.length} chars) -> ${path
      .relative(coreDir, outFile)
      .split(path.sep)
      .join("/")}`
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
